language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
os:
  - linux
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
  - "~/.npm"
notifications:
  email: false
script:
  - yarn test:ci
jobs:
  include:
    - stage: NPM Vet
      node_js: "8"
      before_script:
        - yarn global add npmvet
      script: yarn verify:npmvet
    - stage: Node Security
      node_js: "8"
      before_script:
        - yarn global add nsp
      script: yarn verify:nsp
    - stage: TSLint
      node_js: "8"
      script: yarn tslint
    - stage: Code Coverage
      node_js: "8"
      script: yarn test:coverage:ci
      after_success:
        - cat ./coverage/lcov.info | coveralls
    - stage: Build and deploy
      node_js: "8"
      before_script:
        - yarn global add greenkeeper-lockfile@1
        - greenkeeper-lockfile-update
      script:
        - yarn ts:build
      after_script:
        - greenkeeper-lockfile-upload
      after_success:
        - yarn semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    - BUILD_LEADER_ID=9
    - secure: RcgkCeRYESeHAHorKwwJ2I6fNTrXGA0SPAFKdcTEP/ncG4DihMkdQgCEi52FEZcEpdOR1a4qUPl/f1MzS3IBL2qB7FFoz2NxX76VP5xR6gBRdgmgKjYwRoUR39DXTeJ3zLGqJjDrXYexSAt7acS7oM5M330s6QMA3e+g3+4z2tWRatUaJ/Mr4FaOPmHGFOLlFcoF1fcifpptp9w5XiAQ4psKg8iwBvYxhTIq2VW0fIdeoVuKS6jq+d+g1b0EKu8pYwoXO9ikkxNJQJpU+HB6WcPYQVLPLVLwQJKdqPWsAJsL13EuI5qVqhcyGZ67k4P7KfqjEIE9wJVG4V27tH8hTySldULF0p4br3kaL915o5klUm25ZvyR6r78TJuoSfXoV4AjuvFqvQH52bPa1/MPqcuLvlpEvONVSX61pgeMU5UsitRRhgbIi1M7F6f05QYorTEly4I8LsaHV90ASCclgzdHvK6VHKyGlyJo38l/Sq8y9H57cFVA4oJ/vlyoARxWFA9WQWKHYQqGEFNJM3uevlzVtC6s6AbPNvI3X59dviLW5BWrRONWF3sQfw1HT7us6wQwm35w2ry0bBfZ8FAQTMqpy7YG6J57olliVAfKgRuZzBSsGnQ79Q7/bV7LaQE9arFlAX/WLwnhfkbG5I/js9BWMQt2IXxucZW4OsZE7OA=
    - secure: VFmolcjUNhSBb8yMK1h2+Pu8tNhi415sT7HbDbS8oyMD0o76r1iSdStfiWxHaZljcd7MztEKQRDsbms7EWEhhJheVBywyuV+BF/shnU8FjXi0fdDgwrkfV940D7qmxShoIdGQu4jb7AbWVEYL1K8q4AO9l1A/15/Fd9OpyoUCAX+FRIpie2O2xU8hBUqACIoOwtBT1n+vxlOTaGqFuKiucFPIEU5pqsr4ZTX92SgBvxsb5XoXvunqzpFK1DJHt4LLIS/5xdBm5zOcnnCQ3dLmVn4Ox9LV6G9JRZGHNQxTsbf+6UCd+GmWzB/6AJOkKePfC2Ez1cUmvjgGC9DgH+wYlUxeqaAmePnc1b6siYfrI2iT8e+bAFdmKJ9KgJE5jgXH70IqNmfadZR96oH0+Ky84l6basdCRNkZpGWpC+/KRKaN93olp3fQeFAne4cbF7aErbEhq0m9/e6Yx0Kzb4/qq4UzDSP+NX1WxpJMBPXCeOvXFwrGhLrVcX6ADmYKQK2md2iyLJuZkf0siT4Q19KZ9lfbbyAP5XXprfHblhxwYHpxUhb+3p4gvuf/X0heuSYlc+HjZCa27zc6lk9XrzZyfMcYj5PPy8ShvSLQjPov8ngIWSEH3J/X97oyfIQz+AgDaIJpgxN/x/nSfRWdovmR8P/9zQErzJJgmQLt37afRQ=
