environment:
  nodejs_version: "8"

cache:
  - '%LOCALAPPDATA%\Yarn -> appveyor.yml'
  - node_modules -> package-lock.json

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm i

test_script:
  - .\bin\run --version
  - .\bin\run --help
  - npm run test

after_test:
  - npm run test --coverage

build: off
